### ISSUE TITLE
Balance not loading - Unable to initialize the API

### ISSUE THREAD

**Issue by morrigan** [ChainSafe/metamask-snap-polkadot#106]
Doesn't seem to be working at all as balance is not displaying. Noted error in the console.

`FATAL: Unable to initialize the API: createType(Metadata):: Unable to create Enum via index 12, in V0, V1, V2, V3, V4, V5, V6, V7, V8, V9, V10, V11 `

**Comment by mpetrunic** [comment]
Seems like spec change and broke polkadot api. We need to bump api version, hopefully its gonna work

**Comment by BeroBurny** [comment]
No longer relevant, at some point of refactoring this issue is resolved.
