### ISSUE TITLE
Investigate Updating to Latest Snap API

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/metamask-snap-polkadot#130]
In [January of 2021](https://medium.com/metamask/breaking-changes-to-the-metamask-provider-are-here-7b11c9388be9), MetaMask made a number of breaking changes to the Snap provider API. The largest change was to remove the injected `window.web3` instance. Additionally, the following breaking changes were made

- Stop 0-padding `eth_chainId` return values for some chains
- Stop emitting `chainIdChanged`, and instead emit `chainChanged`
- Removing `ethereum.publicConfigStore`
- Removing the `ethereum._metamask.isEnabled` experimental method
- Removing the `ethereum._metamask.isApproved` experimental method

This ticket is for tracking an investigation into how these API changes will affect the project in this repository. See [MetaMask's migration guide](https://docs.metamask.io/guide/provider-migration.html) for more details.

**Comment by mpetrunic** [comment]
@danforbes I don't think the right API changes are linked. These are related to dapp development. Snap API changes are buried deep here: https://github.com/MetaMask/snaps-skunkworks/releases but for developers, it's easier to do what we did here: https://github.com/ChainSafe/filsnap/pull/88
