### ISSUE TITLE
[BUG] Can not run project by yarn run demo

### ISSUE THREAD

**Issue by CocDap** [ChainSafe/metamask-snap-polkadot#157]
After I `yarn install` successfully, I can't run project by `yarn run demo`

Issue:
```
Usage Error: Workspace 'polkadot-snap' not found. Did you mean any of the following:
  - @chainsafe/metamask-polkadot-adapter
  - @chainsafe/metamask-polkadot-types
  - @chainsafe/polkadot-snap
  - example
  - root?

$ yarn workspace <workspaceName> <commandName> ...
```

My system:
+ MacOs
+ yarn: `3.2.1`
+ node: `16`

**Comment by ramavats** [comment]
Go to package.json file and update these following lines : 

"build:snap": "yarn workspace @chainsafe/polkadot-snap build",
"build:adapter": "yarn workspace @chainsafe/metamask-polkadot-adapter build",
 "start:snap": "yarn workspace @chainsafe/polkadot-snap serve",

**Comment by mpetrunic** [comment]
I don't think this should be an issue anymore
