### ISSUE TITLE
`enablePolkadotSnap` Returns an Error When Using the Default `networkName`

### ISSUE THREAD

**Issue by danforbes** [ChainSafe/metamask-snap-polkadot#170]
Despite selecting "Westend" as the default network in `snap/src/configuration/predefined.ts`, if the adapter executes its only exposed function, `enablePolkadotSnap()`, without specifying `config.networkName`, then an error will be returned. `enablePolkadotSnap()` should use the default Westend configuration [if the supplied configuration does not specify a network name](https://github.com/ChainSafe/metamask-snap-polkadot/blob/61787c6/packages/adapter/src/index.ts#L27).

**Comment by mpetrunic** [comment]
@danforbes I think we had this discussion before and concluded that developer should specify network name instead of defaulting to some arbitrary value. What would be the usecase for defaulting to arbitrary network? Why westend and not rococco?

**Comment by danforbes** [comment]
I don't disagree that a best way to go would be to force developers to select from a list of known-good networks - if that is possible let's do that. Westend is THE official testnet for Polkadot that is maintained by Parity and has a faucet and stuff; Roccoco is a community-maintained network that doesn't have the same level of support as Westend. Westend stands alone as Polkadot's official testnet - that is why I agree it would be the "right" choice in this case.
