### ISSUE TITLE
Call initiatePolkadotSnap, not enablePolkadotSnap, key is `Snap`, not `metamask-polkadot-snap`.

### ISSUE THREAD

**Issue by rossbulat** [ChainSafe/metamask-snap-polkadot#204]
The README -> Integration steps are stating to call enablePolkadotSnap, but to get it into `injectedWeb3`, initiatePolkadotSnap needs to be called instead - and there is no arg option to pass a config to it.

I have also noticed the key once injected is simply `Snap`, not `metamask-polkadot-snap` (see [this](https://github.com/ChainSafe/metamask-snap-polkadot/blob/e0f3d4fc0be7366c62211e29d3a276e4fab5669e/packages/adapter/src/extension/index.ts#L25))

**Comment by ekenigs** [comment]
Also, it's not possible to pass a chain config to `initPolkadotSnap()` which makes it impossible to use with other networks rather than `westend`.

**Comment by vicoysito** [comment]
@ekenis, that's why I am not able to sign any transaction, transfer any Polkadot or Kusama or staking my dots from my wallet using the snap wallet, westend network looks good but Polkadot or Kusama the transaction communication get stuck and the a time-out error? Do you have any idea how can I transfer my Polkadots to another wallet? is the snap is working for you what version of Firefox or Chrome and Metamask are you using. It's been a week that I can not so anything with my dots. :(

**Comment by ekenigs** [comment]
@vicoysito  I haven't played much with the snap. I just checked the documentation, example, and the code of the snap. I was checking if we can integrate the snap into one of our projects. 
You can get your coins back just by importing the same wallet that the snap is using into another wallet or creating a small script that will transfer your assets to another account. It can be hard or easy depending on your technical level.

**Comment by Lykhoyda** [comment]
Hi @rossbulat and  @ekenigs ! If you want to create a dapp using a polkadot snap you can to use our adapter and the method "enablePolkadotSnap" (https://github.com/ChainSafe/metamask-snap-polkadot/tree/master/packages/adapter).  You can pass the config to this method in the next format:
```ts
interface SnapConfig {
  networkName: 'polkadot' | 'kusama' | 'westend;
  wsRpcUrl?: string;
  addressPrefix?: number;
  unit?: UnitConfiguration;
}

enablePolkadotSnap({ networkName: 'kusama' }, snapId)
```
Here is how we enable the adapter with our Example App 
https://github.com/ChainSafe/metamask-snap-polkadot/blob/e0f3d4fc0be7366c62211e29d3a276e4fab5669e/packages/example/src/services/metamask.ts#L50C7-L50C7

**Comment by ekenigs** [comment]
@Lykhoyda that is true but `enablePolkadotSnap()` is not injecting provider to `window.injectedWeb3` to it can't be used.

**Comment by Lykhoyda** [comment]
@ekenigs the changes are on the way https://github.com/ChainSafe/metamask-snap-polkadot/pull/209  @irubido is taking care of it

**Comment by irubido** [comment]
> @Lykhoyda that is true but `enablePolkadotSnap()` is not injecting provider to `window.injectedWeb3` to it can't be used.
Hi
`enablePolkadotSnap() `is not injecting into injectedWeb3,
`initPolkadotSnap()` is

**Comment by vicoysito** [comment]
> @vicoysito I haven't played much with the snap. I just checked the documentation, example, and the code of the snap. I was checking if we can integrate the snap into one of our projects. You can get your coins back just by importing the same wallet that the snap is using into another wallet or creating a small script that will transfer your assets to another account. It can be hard or easy depending on your technical level.

Thanks for your response @ekenigs, is there any example or tutorial you can share with me?

**Comment by ekenigs** [comment]
@vicoysito I don't think that there is a tutorial for that. I can just give you some hints.
1. You need to get the same key as a Keyring key pair https://github.com/ChainSafe/metamask-snap-polkadot/blob/bf7a3a3b936eb55487c8dd3472c5de1457a96987/packages/snap/src/polkadot/account.ts#L14 and hehttps://github.com/MetaMask/key-tree/blob/main/README.md?plain=1#L47
2. Make a transfer https://polkadot.js.org/docs/api/start/api.tx/
