### ISSUE TITLE
Error when using custom network

### ISSUE THREAD

**Issue by thesan** [ChainSafe/metamask-snap-polkadot#231]
When using a custom network the snap returns an error: `Invalid configuration schema - Network name should be provided` even though a network name was specified.

When connecting from a DApp the snap appears to still work anyway but the error still appears in the console.
E.g: https://pioneer-2-git-feature-metamask-snap-joystream.vercel.app

However when I run the snap locally or [publish it myself](https://www.npmjs.com/package/@thesan/polkadot-snap) this does not happen.

Is this the expected behavior for the published version of the snap ? If so could the error be more explicit ?

**Comment by thesan** [comment]
Hi @irubido,

Yes you're right the issue is fixed now.

Thank you :pray:

**Comment by kdembler** [comment]
Hey @irubido, hope you are doing well! Just following up on that, it's been almost a month since the Github 0.9.0 release but the snap store is still at 0.8.2, is the audit expected to take that long?
