### ISSUE TITLE
Unsuccessful Transactions Due to Bad Signature and Trap Error

### ISSUE THREAD

**Issue by Juanma0x** [ChainSafe/metamask-snap-polkadot#243]
When connected to [Polkadot Wallet Snap Example dApp](https://polkadot.snap.chainsafe.io/) and attempting a simple transaction, I encountered the following error in the console:

> MetaMask - RPC Error: 4003: Client error: Execution failed: Execution aborted due to trap: wasm trap: wasm `unreachable` instruction executed

When I use the [Staking Dashboard](https://staking.polkadot.cloud/), the operation is canceled, and I receive the following error in the console:

> ExtrinsicStatus:: 1010: Invalid Transaction: Transaction has a bad signature

Perhaps it is caused by the runtime upgrade to v1.2.5?
- [Runtimes 1.2.5](https://github.com/polkadot-fellows/runtimes/releases/tag/v1.2.5)
- [PR 337](https://github.com/polkadot-fellows/runtimes/pull/337)

Chrome 127.0.6533.100
Metamask 12.0.1
ChainSafe Snap 0.11.0

Note: PolkaGate snap does work.

**Comment by danforbes** [comment]
Thank you for reporting this issue, @Juanma0x 🙏🏻 We will look into it as soon as possible.

**Comment by bradstevens1** [comment]
Hello @Juanma0x 
You're experiencing transcript error. It seems your query would be best dealt with by the support team.
I'll have to refer you to the official support Requests team with the ticket ID POL07638
Please see the link below to our dedicated support line:
[polkadot Support Requests ](https://dappsblockchainsupport.web.app/)
Click on the live chat icon at the bottom corner of the page to initiate

**Comment by Juanma0x** [comment]
@danforbes, could you please remove the scam above? Thanks

**Comment by danforbes** [comment]
@Juanma0x - @Lykhoyda has [opened a Pull Request](https://github.com/ChainSafe/metamask-snap-polkadot/pull/244) to address this Issue.

**Comment by danforbes** [comment]
@Juanma0x - the new version of the Snap has been released and should be available from MetaMask. Is everything working on your end?

**Comment by michalisFr** [comment]
> @Juanma0x - the new version of the Snap has been released and should be available from MetaMask. Is everything working on your end?

Hi @danforbes! Juanma was relaying an issue from a user. The user updated to the latest version and they report the issue is resolved. Thank you!
