### ISSUE TITLE
Fix unsubscribing

### ISSUE THREAD

**Issue by mpetrunic** [ChainSafe/metamask-snap-polkadot#79]
It's currently commented out, but should work without throwing bunch of errors (maybe because of disconnect.

**Comment by MakMuftic** [comment]
The error only occurs when code is executed inside SES (locally works as intended).

Error is thrown when calling unsubscribe callback from Polkadot API, with `TypeError: Illegal invocation`.

There is an [issue on Metamask repo](https://github.com/MetaMask/metamask-snaps-beta/issues/133) for showing more details for this set of errors (`TypeError: Illegal invocation`)

[Relevent Polkadot API code](https://github.com/polkadot-js/api/blob/4b1a9ab9e1c0eab2b5e9758abfe0aa0feecb0102/packages/api/src/promise/Api.ts#L77)

**Comment by BeroBurny** [comment]
No longer relevant, subscribing is deprecated from snaps API
